services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - ${BACKEND_PORT}:3000
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - PROXY_PORT=${PROXY_PORT}
      - CHROME_ARGS=--no-sandbox --disable-setuid-sandbox
    volumes:
      - ${BACKEND_PUBLIC_DIR}:/usr/src/app/public/
      - ${BACKEND_WWEBJS_AUTH_DIR}:/usr/src/app/.wwebjs_auth/
    networks:
      - whaticket

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - ${FRONTEND_PORT}:80
      - ${FRONTEND_SSL_PORT}:443
    environment:
      - URL_BACKEND=${URL_BACKEND}
      - REACT_APP_BACKEND_URL=${BACKEND_URL}:${PROXY_PORT}/
      - FRONTEND_SERVER_NAME=${FRONTEND_SERVER_NAME}
      - BACKEND_SERVER_NAME=${BACKEND_SERVER_NAME}
    volumes:
      - ${SSL_CERTS_DIR}:/etc/nginx/ssl/
      - ${SSL_WWW_DIR}:/var/www/letsencrypt/
    networks:
      - whaticket
    depends_on:
      - backend

networks:
  whaticket:
