services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - PROXY_PORT=${PROXY_PORT}
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_PUBLIC_DIR=${BACKEND_PUBLIC_DIR}
      - BACKEND_WWEBJS_AUTH_DIR=${BACKEND_WWEBJS_AUTH_DIR}
      - CHROME_ARGS=${CHROME_ARGS}
    volumes:
      - ${BACKEND_PUBLIC_DIR}:/usr/src/app/public/
      - ${BACKEND_WWEBJS_AUTH_DIR}:/usr/src/app/.wwebjs_auth/
    networks:
      - whaticket

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
        - REACT_APP_HOURS_CLOSE_TICKETS_AUTO=${REACT_APP_HOURS_CLOSE_TICKETS_AUTO}
    ports:
      - ${FRONTEND_PORT}:80

    networks:
      - whaticket
    depends_on:
      - backend

networks:
  whaticket:
